spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/travelplanner?useSSL=false
    username: postgres
    password: semrakermo
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false